blank_issues_enabled: false
contact_links:
  - name: ğŸ“¨ kyoulee ê¹ƒí—ˆë¸Œ í”„ë¡œí•„
    url: https://github.com/kyoulee/
    about: Please ask and answer questions here.
  - name: ğŸŒ kyoulee í”„ë¡œì íŠ¸
    url: https://github.com/users/kyoulee/projects/1
    about: Please report security vulnerabilities here.
